# Generated by Django 5.0 on 2024-03-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='account',
        ),
    ]
